controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

api_controllers:
    name_prefix: api_
    prefix: /api
    resource: ../../src/Controller/Api
    type: annotation